In [1]:
import os
from pathlib import Path
os.chdir(r"D:\teleco-churn-project\teleco-churn")

In [2]:
from src.preprocess import (
    load_data,
    clean_data,
    split_feature,
    preprocess_data,
    convert_processor_to_df
)

In [3]:
os.getcwd()

'D:\\teleco-churn-project\\teleco-churn'

In [4]:
path = r"D:\teleco-churn-project\teleco-churn\data\raw\Churn.csv"
print(os.path.exists(path))

True

In [5]:
data=load_data(path)

In [6]:
data.columns

Index(['Account_Length', 'Vmail_Message', 'Day_Mins', 'Eve_Mins', 'Night_Mins',
       'Intl_Mins', 'CustServ_Calls', 'Churn', 'Intl_Plan', 'Vmail_Plan',
       'Day_Calls', 'Day_Charge', 'Eve_Calls', 'Eve_Charge', 'Night_Calls',
       'Night_Charge', 'Intl_Calls', 'Intl_Charge', 'State', 'Area_Code',
       'Phone'],
      dtype='object')

In [7]:
data.head()

,Account_Length,Vmail_Message,Day_Mins,Eve_Mins,Night_Mins,Intl_Mins,CustServ_Calls,Churn,Intl_Plan,Vmail_Plan,...,Day_Charge,Eve_Calls,Eve_Charge,Night_Calls,Night_Charge,Intl_Calls,Intl_Charge,State,Area_Code,Phone
0,128,25,265.1,197.4,244.7,10.0,1,no,no,yes,...,45.07,99,16.78,91,11.01,3,2.70,KS,415,382-4657
1,107,26,161.6,195.5,254.4,13.7,1,no,no,yes,...,27.47,103,16.62,103,11.45,3,3.70,OH,415,371-7191
2,137,0,243.4,121.2,162.6,12.2,0,no,no,no,...,41.38,110,10.30,104,7.32,5,3.29,NJ,415,358-1921
3,84,0,299.4,61.9,196.9,6.6,2,no,yes,no,...,50.90,88,5.26,89,8.86,7,1.78,OH,408,375-9999
4,75,0,166.7,148.3,186.9,10.1,3,no,yes,no,...,28.34,122,12.61,121,8.41,3,2.73,OK,415,330-6626

In [8]:
data=clean_data(data)

In [9]:
data.head()

,Account_Length,Vmail_Message,CustServ_Calls,Churn,Intl_Plan,Vmail_Plan,State,Area_Code,Total_cals,total_charges
0,128,25,1,no,no,yes,KS,415,303,75.56
1,107,26,1,no,no,yes,OH,415,332,59.24
2,137,0,0,no,no,no,NJ,415,333,62.29
3,84,0,2,no,yes,no,OH,408,255,66.80
4,75,0,3,no,yes,no,OK,415,359,52.09

In [10]:
data.shape

(3333, 10)

In [11]:
x=data.drop(['Churn'],axis=1)
y=data['Churn']

In [12]:
numarical_data,categorical_data=split_feature(x)

In [13]:
numarical_data

['Account_Length',
 'Vmail_Message',
 'CustServ_Calls',
 'Area_Code',
 'Total_cals',
 'total_charges']

In [14]:
categorical_data

['Intl_Plan', 'Vmail_Plan', 'State']

In [15]:
processor=preprocess_data(numarical_data,categorical_data)

In [16]:
processed_data=processor.fit_transform(x,y)

In [17]:
new_data=convert_processor_to_df(processor,processed_data)

In [18]:
new_data.head()

,num__Account_Length,num__Vmail_Message,num__CustServ_Calls,num__Area_Code,num__Total_cals,num__total_charges,cat__Intl_Plan_no,cat__Intl_Plan_yes,cat__Vmail_Plan_no,cat__Vmail_Plan_yes,...,cat__State_SD,cat__State_TN,cat__State_TX,cat__State_UT,cat__State_VA,cat__State_VT,cat__State_WA,cat__State_WI,cat__State_WV,cat__State_WY
0,0.676489,1.234883,-0.427932,-0.523603,-0.062048,1.534209,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.149065,1.307948,-0.427932,-0.523603,0.779923,-0.019975,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.902529,-0.591760,-1.188218,-0.523603,0.808957,0.270482,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-0.428590,-0.591760,0.332354,-0.688834,-1.455655,0.699978,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-0.654629,-0.591760,1.092641,-0.523603,1.563827,-0.700883,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
new_data.shape

(3333, 61)

In [19]:
for col in x.select_dtypes(include="object").columns:
    print(col, x[col].nunique())

Intl_Plan 2
Vmail_Plan 2
State 51

In [21]:
print("Churn in features:", "Churn" in x.columns)

Churn in features: False

In [23]:
for col in categorical_data:
    print(col, x[col].nunique())

Intl_Plan 2
Vmail_Plan 2
State 51

In [24]:
print(len(processor.get_feature_names_out()))

61

In [26]:
new_data.head()

,num__Account_Length,num__Vmail_Message,num__CustServ_Calls,num__Area_Code,num__Total_cals,num__total_charges,cat__Intl_Plan_no,cat__Intl_Plan_yes,cat__Vmail_Plan_no,cat__Vmail_Plan_yes,...,cat__State_SD,cat__State_TN,cat__State_TX,cat__State_UT,cat__State_VA,cat__State_VT,cat__State_WA,cat__State_WI,cat__State_WV,cat__State_WY
0,0.676489,1.234883,-0.427932,-0.523603,-0.062048,1.534209,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.149065,1.307948,-0.427932,-0.523603,0.779923,-0.019975,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.902529,-0.591760,-1.188218,-0.523603,0.808957,0.270482,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-0.428590,-0.591760,0.332354,-0.688834,-1.455655,0.699978,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-0.654629,-0.591760,1.092641,-0.523603,1.563827,-0.700883,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
y.shape

(3333,)

In [33]:
new_data['churn']=y

In [34]:
new_data.head()

,num__Account_Length,num__Vmail_Message,num__CustServ_Calls,num__Area_Code,num__Total_cals,num__total_charges,cat__Intl_Plan_no,cat__Intl_Plan_yes,cat__Vmail_Plan_no,cat__Vmail_Plan_yes,...,cat__State_TN,cat__State_TX,cat__State_UT,cat__State_VA,cat__State_VT,cat__State_WA,cat__State_WI,cat__State_WV,cat__State_WY,churn
0,0.676489,1.234883,-0.427932,-0.523603,-0.062048,1.534209,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no
1,0.149065,1.307948,-0.427932,-0.523603,0.779923,-0.019975,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no
2,0.902529,-0.591760,-1.188218,-0.523603,0.808957,0.270482,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no
3,-0.428590,-0.591760,0.332354,-0.688834,-1.455655,0.699978,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no
4,-0.654629,-0.591760,1.092641,-0.523603,1.563827,-0.700883,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no

In [35]:
new_data['churn']=new_data['churn'].map({'no':0,'yes':1})

In [36]:
new_data.head()

,num__Account_Length,num__Vmail_Message,num__CustServ_Calls,num__Area_Code,num__Total_cals,num__total_charges,cat__Intl_Plan_no,cat__Intl_Plan_yes,cat__Vmail_Plan_no,cat__Vmail_Plan_yes,...,cat__State_TN,cat__State_TX,cat__State_UT,cat__State_VA,cat__State_VT,cat__State_WA,cat__State_WI,cat__State_WV,cat__State_WY,churn
0,0.676489,1.234883,-0.427932,-0.523603,-0.062048,1.534209,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,0.149065,1.307948,-0.427932,-0.523603,0.779923,-0.019975,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,0.902529,-0.591760,-1.188218,-0.523603,0.808957,0.270482,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,-0.428590,-0.591760,0.332354,-0.688834,-1.455655,0.699978,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,-0.654629,-0.591760,1.092641,-0.523603,1.563827,-0.700883,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [37]:
new_data['churn'].unique()

array([0, 1], dtype=int64)

In [39]:
new_data['churn'].value_counts()

churn
0    2850
1     483
Name: count, dtype: int64

In [38]:
new_data.to_csv("processed_data.csv", index=False)